# -*- coding: utf-8 -*-
"""Triângulo de Pascal

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1bjTaGe8Ecd5Y4YLTayFc9Il5yUKbsKJo
"""

def get_int(msg):
  while True:
    try:
      n = int(input(msg))
    except:
      pass
    else:
      if n > 0:
        return n
 
 
lines = get_int("Digite quantas linhas você quer do triângulo: ")
lines += 1
previous_line = []
current_line = []
pascal_triangle = [[1]]
for c in range(lines):
  previous_line = current_line[:]
  current_line.clear()
  for i in range(c):
    if i == 0 or i == c - 1:
      num = 1
      current_line.append(num)
    else:
      num = previous_line[i-1] + previous_line[i]
      current_line.append(num)
    print(f'{num:<6}', end=' ')
  print()